[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.26"

[rpc_endpoints]
mainnet_rpc = "${MAINNET_RPC_URL}"

[fmt]
line_length = 120
tab_width = 4
bracket_spacing = true
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
